# Generated by Django 6.0.6 on 2026-09-17 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Investor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("occupation", models.CharField(max_length=150)),
                ("interest_area", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("college", models.CharField(max_length=150)),
                ("skill", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Idea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=200)),
                ("description", models.TextField(default="")),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("idea", "Sirf idea hai"),
                            ("prototype", "Prototype ban raha hai"),
                            ("mvp", "MVP ready hai"),
                            ("scaling", "Users hain, ab scale karna hai"),
                        ],
                        default="idea",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tech", "Tech / SaaS"),
                            ("ecommerce", "E-commerce"),
                            ("service", "Service / booking"),
                            ("education", "Education"),
                            ("health", "Health"),
                            ("other", "Doosra"),
                        ],
                        default="tech",
                        max_length=20,
                    ),
                ),
                ("help_needed", models.CharField(blank=True, max_length=200)),
                ("name", models.CharField(default="", max_length=100)),
                ("college", models.CharField(blank=True, max_length=150)),
                ("contact", models.CharField(default="", max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ideas",
                        to="prtapp.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
