# Generated by Django 6.0.6 on 2026-09-19 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prtapp", "0002_connectionrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamFinder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hackathon_name", models.CharField(max_length=200)),
                ("my_role", models.CharField(max_length=100)),
                ("looking_for", models.CharField(max_length=200)),
                ("project_description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "looking",
                                "Looking for Teammate (Teammate dhoondh raha hai)",
                            ),
                            ("matched", "Matched / Team Formed (Team ban gayi hai)"),
                            ("closed", "Closed (Band ho gaya)"),
                        ],
                        default="looking",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_profiles",
                        to="prtapp.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
